# Generated by Django 6.0.1 on 2026-01-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pastes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paste",
            name="created_at",
        ),
    ]
