# Generated by Django 6.0.1 on 2026-01-27 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pastes", "0002_remove_paste_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="paste",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
